spring:
  config:
    activate:
      on-profile: default
# eureka:
#   instance:
#     # enable to register multiple app instances with a random server port
#     instance-id: ${spring.application.name}:${random.uuid}
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:80/
---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    enabled: false
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server/
