vets:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:80/
# eureka:
#   instance:
#     # enable to register multiple app instances with a random server port
#     instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    enabled: false
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:80/
